package com.goodkredit.myapplication.enums;
//-----------CREATED ON: 11/26/2018 (mm/dd/yy)----------------

//UPDATED ON: 12/17/2018 (mm/dd/yy)
//SUCCESS -> THEME: GREEN, USED FOR SUCCESS DIALOG
//FAILED -> THEME: RED, USED FOR FAILED DIALOG
//TIMEOUT -> THEME: ORANGE, USED FOR TIMEOUT DIALOG
//ONPROCESS -> THEME: YELLOW, USED FOR ONPROCESS DIALOG
//QRCODE -> THEME: BLUE, USED FOR QRCODE DIALOG
//IMAGE -> THEME: DYNAMIC, USED FOR IMAGE DIALOG
//TEXT -> THEME: DYNAMIC, USED FOR TEXT DIALOG
//NOTICE -> THEME: BLUE, USED FOR NOTICE DIALOG
//WARNING -> THEME: YELLOW, USED FOR WARNING DIALOG
//RADIO -> THEME: BLUE, USED FOR RADIO (SINGLE CHOICE) DIALOG
//TEXTVIEW ->THEME: BLUE, USED FOR TEXT DIALOG
//DOUBLETEXTVIEW -> THEME: BLUE, USED FOR DOUBLETEXTVIEW DIALOG
//RADIO -> THEME: BLUE, USED FOR CREATING MULTIPLE RADIO (SINGLE CHOICE) DIALOG
//EDITTEXT -> THEME: BLUE, USED FOR CREATING EDITTEXT DIALOG
//SPINNER -> THEME: BLUE, USED FOR CREATING SPINNER DIALOG
//CUSTOMCONTENT -> THEME: BLUE, USED FOR CREATING CUSTOMCONTENT DIALOG

public enum DialogTypeEnum {
    SUCCESS,
    FAILED,
    TIMEOUT,
    ONPROCESS,
    QRCODE,
    IMAGE,
    TEXT,
    NOTICE,
    WARNING,
    TEXTVIEW,
    DOUBLETEXTVIEW,
    RADIO,
    EDITTEXT,
    SPINNER,
    CUSTOMCONTENT
}



